### ISSUE TITLE
Set up ollama docker container

### ISSUE THREAD

**Issue by chris4727** [chris4727/ollama-container#1]
- [x] Setup min working example

# [Example compose.yml](https://gist.github.com/notthebee/1dfc5a82d13dd2bb6589a1e4747e03cf)

```yaml
---
services:
  webui:
    image: ghcr.io/open-webui/open-webui:main
    ports:
     - 8080:8080/tcp
    environment:
     - OLLAMA_BASE_URL=http://ollama:11434
    volumes:
      - /var/opt/data/ollama/webui:/app/backend/data
    depends_on:
     - ollama

  ollama:
    image: ollama/ollama:rocm
    ports:
     - 11434:11434/tcp
    volumes:
      - /var/opt/data/ollama/ollama:/root/.ollama
    devices:
      - /dev/kfd
      - /dev/dri
```

# References

- [Wolfgang's Channel: Host Your Own AI Code Assistant with Docker, Ollama and Continue!](https://www.youtube.com/watch?v=OpmMe0md0tA)
- [Using Ollama on older AMD GPUs with ROCM](https://medium.com/@afilipe362/using-ollama-on-older-amd-gpus-with-rocm-on-windows-a0b08de2cf02)
